version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/cli"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/core"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/vscode-extension"
    schedule:
      interval: "daily"
