ignorePatterns:
  - dist
  - out
parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: module
rules:
  "@typescript-eslint/naming-convention": warn
  curly: warn
  eqeqeq: warn
  no-throw-literal: warn
