env:
  es6: true
  node: true
extends:
- eslint:recommended
- plugin:@typescript-eslint/eslint-recommended
- plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
ignorePatterns:
- bin/run.js
- cache/
- cache-*/
- src/utils/escape-string-regexp.ts
- test/*.test/
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
- "@typescript-eslint"
- jest
rules:
  indent:
  - error
  - 4
  - SwitchCase: 1
  linebreak-style:
  - error
  - unix
  quotes: 'off'
  semi:
  - error
  - never
  "@typescript-eslint/explicit-module-boundary-types": 'off'
  "jest/no-disabled-tests": "warn"
  "jest/no-focused-tests": "error"
  "jest/no-identical-title": "error"
  "jest/prefer-to-have-length": "warn"
  "jest/valid-expect": "error"
