extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
ignorePatterns:
  - cache*/
  - out/
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
overrides:
  - files: ['*(!.d).ts']
    parserOptions:
      project:
      - tsconfig.json
    rules:
      "@typescript-eslint/no-floating-promises": error
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-return-await: 'off'  # optimization only and harder to read
  no-trailing-spaces: error
  no-unnecessary-initializer: 'off'  # readability
  quotes: 'off'
  require-yield: 'off'
  semi:
    - error
    - never
  "@typescript-eslint/explicit-module-boundary-types": 'off'
  "@typescript-eslint/no-explicit-any":
    - warn
    - ignoreRestArgs: true
  "@typescript-eslint/no-unused-vars":
    - warn
    - args: none
  "@typescript-eslint/return-await":
    - error
    - always
  "jest/no-disabled-tests": "warn"
  "jest/no-focused-tests": "error"
  "jest/no-identical-title": "error"
  "jest/prefer-to-have-length": "warn"
  "jest/valid-expect": "error"
