ignorePatterns:
  - out
  - dist
  # - **/*.d.ts
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  "@typescript-eslint/naming-convention": warn
  curly: warn
  eqeqeq: warn
  no-throw-literal: warn
