env:
  es6: true
  node: true
ignorePatterns:
- cache/
- cache-*/
- test/**/*.test/
- samples/
- jest.config.ts
parserOptions:
  ecmaVersion: 2020
  project:
  - tsconfig.json
  - test/tsconfig.json
  sourceType: module
