name: Test cli

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install && yarn build
        working-directory: ./packages/core
      - run: npm install  # yarn does not support file dependencies correctly ...
      - run: git diff --exit-code package-lock.json || (echo "package-lock.json was changed" && exit 1)
      - run: npm run test
        env:
          GITHUB_OAUTH_TOKEN: ${{ github.token }}
          SOURCEGRAPH_TOKEN: ${{ secrets.SOURCEGRAPH_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
        working-directory: .
      - run: npm install  # yarn does not support file dependencies correctly ...
      - run: yarn lint
