name: rebase dependabot pull requests
on:
  push:
    branches:
      - refs/heads/master

jobs:
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: LinqLover/gha-auto-dependabot-rebase@feat/one-at-a-time
        with:
          one-at-a-time: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_DEPENDABOT_AUTO_REBASE_PRS }}
