name: rebase dependabot pull requests
on: [push]
jobs:
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: LinqLover/gha-auto-dependabot-rebase@feat/one-at-a-time
        with:
          one-at-a-time: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_DEPENDABOT_AUTO_REBASE_PRS }}
