name: ✒ Paper

on:
  push:
    paths:
      - docs/paper/**
      - scripts/docs/**
      - .github/workflows/docs.paper.yml

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.tex
          working_directory: docs/paper
