name: Exposé

on: push

jobs:
  pandoc:
    runs-on: ubuntu-latest
    container: songritk/xelatex
    steps:
      - run: ./scripts/docs/md2pdf.sh docs/exposé.md scripts/docs/pandoc.yml --citeproc -o docs/exposé.pdf
  upload:
    needs: [pandoc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@master
        with:
          name: exposé
          path: exposé.pdf
