name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/setup
      - run: ./scripts/test-cli.sh
      - run: yarn test
        env:
          GITHUB_OAUTH_TOKEN: ${{ github.token }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/setup
      - run: yarn lint
