name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: ./scripts/test-cli.sh
      - run: yarn test
        env:
          GITHUB_OAUTH_TOKEN: ${{ github.token }}
