name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: git diff --exit-code yarn.lock || (echo "yarn.lock was changed" && exit 1)
      - run: ./scripts/test-cli.sh
      - run: ./scripts/test-examples.sh
      - run: yarn test
        env:
          GITHUB_OAUTH_TOKEN: ${{ github.token }}
  test-vscode-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd src/vscode-extension
      - run: yarn install
      - run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lint
